### ISSUE TITLE
Update company description: Facebook is now Meta

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/trackerdb#101]
Here is the entry for Meta:
https://github.com/ghostery/trackerdb/blob/main/db/organizations/facebook.eno

We can keep the internal filename `facebook.eno`, but the company name and description should be updated. Mentioning Facebook in the company description makes sense, but Meta is not only operating Facebook any more (e.g. Instagram is worth mentioning)

**Comment by Switch0XD** [comment]
Hello @philipp-classen,
Please assign this task to me. I'll update the description in while.
Thanks
