### ISSUE TITLE
Update company description: Twitter is now X Corp.

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/trackerdb#102]
Twitter is now [X Corp.](https://en.wikipedia.org/wiki/X_Corp.)

Here is its entry:
https://github.com/ghostery/trackerdb/blob/main/db/organizations/twitter.eno

We can keep the internal filename `twitter.eno`, but the company name and description should be updated.

**Comment by dtee1** [comment]
#104

**Comment by philipp-classen** [comment]
> I created a PR for this issue #104. Also, you could assign this to me

Thanks a lot! I'll have a look at it soon.

**Comment by philipp-classen** [comment]
Thanks for the help, @dtee1! With the next monthly update, your changes should also become visible on WhoTracks.me (e.g. this page should update https://whotracks.me/trackers/twitter.html#)

**Comment by dtee1** [comment]
It's my pleasure. I am available if you need further help.
