### ISSUE TITLE
[Unidentified Tracker]: mon.tiktokv.com

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/trackerdb#128]
### Request

mon.tiktokv.com

### Location

https://www.tiktok.com/explore

### Tracker Company

TikTok

### Company Website

https://www.tiktok.com/

### Privacy Policy

https://www.tiktok.com/legal/page/eea/privacy-policy/en

### Describe the company

TikTok is a social media company known for its short-form video platform. It allows users to create and share short videos, typically ranging from 15 seconds to one minute in length.

### Category

None

### Request Type

None

**Comment by philipp-classen** [comment]
It should be covered now. The effects will be only visible after releases of the Ghostery Extension.
