### ISSUE TITLE
[Unidentified Tracker]: www.recaptcha.net

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/trackerdb#129]
### Request

www.recaptcha.net

### Location

https://www.pinterest.com/

### Category

None

### Request Type

None

**Comment by philipp-classen** [comment]
To trigger: Go to https://www.pinterest.com/ and try to log in

**Comment by philipp-classen** [comment]
It should be covered now. The effects will be only visible after releases of the Ghostery Extension.
