### ISSUE TITLE
[Unidentified Tracker]: www.clarity.ms

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/trackerdb#134]
### Request

www.clarity.ms

### Location

https://www.rattanebike.com/

### Tracker Company

Microsoft

### Company Website

https://www.microsoft.com/

### Privacy Policy

https://privacy.microsoft.com/en-gb/privacystatement

### Category

None

### Request Type

None

**Comment by philipp-classen** [comment]
@chrmod I am surprised that it is not covered by this existing entry: https://github.com/ghostery/trackerdb/blob/af226f3e23ea889075535aaba2c283d10f0282ed/db/patterns/microsoft_clarity.eno#L18

**Comment by philipp-classen** [comment]
Regarding the matching, see https://github.com/ghostery/ghostery-extension/issues/1332

**Comment by philipp-classen** [comment]
With the following change, it is no longer using subdomain, which is arguably correct here and will avoid the matching issue:https://github.com/ghostery/trackerdb/commit/bca2e078c45f93c7ca6c2a3e1cc55040745bb31f

**Comment by philipp-classen** [comment]
In local builds, it is detected now:
![clarity](https://github.com/ghostery/trackerdb/assets/1616509/61b621ed-815a-46c8-801d-6cbecc7a3f32)
