### ISSUE TITLE
[Unidentified Tracker]: js.monitor.azure.com

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/trackerdb#145]
### Request

js.monitor.azure.com

### Location

https://www.msn.com/

### Tracker Company

Microsoft

### Company Website

https://azure.microsoft.com/en-gb/

### Privacy Policy

https://privacy.microsoft.com/en-gb/privacystatement

### Category

None

### Request Type

None

**Comment by philipp-classen** [comment]
It should be covered now. The effects will be only visible after releases of the Ghostery Extension.
