### ISSUE TITLE
[Unidentified Tracker]: Gainsight PX

### ISSUE THREAD

**Issue by aaronhatton** [ghostery/trackerdb#150]
### Request

aptrinsic.com

### Location

https://community.insided.com/

### Tracker Company

Gainsight PX

### Company Website

Gainsight Inc.

### Privacy Policy

https://www.gainsight.com/policy/privacy/

### Category

Customer Interaction

### Request Type

script

### Additional Information

This tool is typically used for app interaction tracking and customer engagement delivery. This includes personalized messaging within both the app and email (if signed in).

**Comment by philipp-classen** [comment]
It should be covered now. The effects will be only visible after releases of the Ghostery Extension.
