### ISSUE TITLE
fbevents.js

### ISSUE THREAD

**Issue by FilipeF12** [ghostery/trackerdb#154]
### Request

www.daz3d.com

### Location

www.daz3d.com

### Tracker Company

meta

### Company Website

www.meta.com

### Describe the company

meta, facebook

### Category

Social Media

### Request Type

beacon

### Filters

```shell
not sure. would require targeted javascript blocking
```

**Comment by philipp-classen** [comment]
It should be covered now. The effects will be only visible after releases of the Ghostery Extension.

**Comment by FilipeF12** [comment]
Thanks!
 

Sent: Tuesday, January 23, 2024 at 5:46 AM
