### ISSUE TITLE
[Unidentified Tracker]: ethyca.com

### ISSUE THREAD

**Issue by NevilleS** [ghostery/trackerdb#155]
### Request

ethyca.com

### Location

https://privacy.misfitsmarket.com

### Tracker Company

Ethyca

### Company Website

https://ethyca.com/

### Privacy Policy

https://privacy.ethyca.com/

### Describe the company

Ethyca is a data privacy company and maintainer of the Fides open source privacy engineering platform (github.com/fides) and provides tools to help organizations support data privacy in their products, including features like consent management, data subject access requests, data mapping, and "privacy-as-code" developer tools.

### Category

Consent Management

### Request Type

script

### Additional Information

Ethyca is used by many organizations to implement data privacy features into their platform such as:
* https://privacy.misfitsmarket.com
* https://privacy.awaytravel.com
* https://casper.com
* https://nextjs.org/
* etc.

In all these cases, Ethyca provides a Javascript package that sites can include to implement consent management banners, add support for Global Privacy Control, etc.

### Filters

```shell
||ethyca.com^$third-party
```

**Comment by NevilleS** [comment]
FYI: I am on the team at [Ethyca](https://ethyca.com/) and would like to self-register our domain here so that we aren't unidentified in Ghostery 👍! Happy to answer questions.

**Comment by philipp-classen** [comment]
@NevilleS Thanks a lot! I created a pull request for it:  https://github.com/ghostery/trackerdb/pull/156

If it looks alright, I'll merge it.

**Comment by NevilleS** [comment]
Taking a look, thanks!

**Comment by philipp-classen** [comment]
Merged now. You should be able to test with the next release of the Ghostery extension. And next month, it should show up in WhoTracks.me

I'll let you know when it is ready to test. We can leave the ticket open until then.

**Comment by NevilleS** [comment]
Great, thanks! How often does Ghostery run those releases?

**Comment by philipp-classen** [comment]
> Great, thanks! How often does Ghostery run those releases?

That varies. But I think, it is likely that it gets released till the end of month.

**Comment by NevilleS** [comment]
Sounds good to me, thanks @philipp-classen 😄

**Comment by philipp-classen** [comment]
> I'm seeing this on the Ghostery extension now, looks good!

Yes, we had a releases (e.g. Chrome). One thing that is still missing is the monthly WhoTracks.me release (at the start of the month). Then Ghostery should also include the company description.

**Comment by philipp-classen** [comment]
I do not see it yet on WhoTracks.me. There are thresholds, perhaps the traffic seen so far was not enough?

The entry in TrackerDB itself looks fine, so I'll close it. I opened a ticket on WhoTracks.me to document the current behavior (https://github.com/whotracksme/whotracks.me/issues/338).
