### ISSUE TITLE
Cookieinformation.com - cookie consent tracker

### ISSUE THREAD

**Issue by FarligOrm** [ghostery/trackerdb#161]
### Request

policy.app.cookieinformation.com

### Location

build.aau.dk

### Tracker Company

Cookieinformation.com

### Company Website

cookieinformation.com

### Privacy Policy

policy.app.cookieinformation.com

### Describe the company

"_Offer your website visitors transparency and give them control over what data is collected about them. Website Consent ensures compliance with laws like GDPR & CCPA without compromising your marketing performance._ "

### Category

Consent Management

### Request Type

None

**Comment by philipp-classen** [comment]
It should be covered now. The effects will be only visible after releases of the Ghostery Extension.
