### ISSUE TITLE
CookieFirst

### ISSUE THREAD

**Issue by cookiefirst** [ghostery/trackerdb#207]
### Request

consent.cookiefirst.com

### Location

https://laeppche.de/

### Tracker Company

CookieFirst

### Company Website

https://cookiefirst.com

### Privacy Policy

https://cookiefirst.com/legal/privacy-policy/

### Describe the company

CookieFirst is a Consent Mangement Platform enabling website owners to comply with various privacy legislations like GDPR, ePR, CCPA and LGPD. It helps website owners block scripts and cookies before consent.

### Category

Consent Management

### Request Type

None

**Comment by seia-soto** [comment]
Hi, thank you for your effort to improve the transparency of the web. We've added CookieFirst to our organization and pattern definitions according to your information.
