### ISSUE TITLE
Issue with POST request by another browser extension

### ISSUE THREAD

**Issue by rnatella** [ghostery/trackerdb#343]
Hi,

I am using Ghostery on Microsoft Edge (125.0.2535.79) on Mac OS (12.7.4).

When I share a message with the Pushbullet extension, the request is blocked (see screenshots).
If I turn off Ghostery, the message is allowed to pass.

In the configuration panel, under "tracker", the website "pushbullet.com" looks like not blocked.

Do you have any other way to white-list this website in Ghostery?

![image](https://github.com/ghostery/trackerdb/assets/2117196/0932bbd8-e17a-4f98-9c05-805981753267)
![image](https://github.com/ghostery/trackerdb/assets/2117196/2a2f10ce-912f-4df3-b946-a39381b4516e)
![image](https://github.com/ghostery/trackerdb/assets/2117196/ddf0dba3-2ee0-4c24-a4d9-3ed56904ec6a)

(updated with more screenshots of JS code)

**Comment by philipp-classen** [comment]
Thanks for reporting.

There is one entry in TrackerDB, but it does not match the request (just mentioning for completeness):
https://github.com/ghostery/trackerdb/blob/main/db/patterns/pushbullet.eno

Coming back to the breakage. I do not have a realistic test setup, but I could reproduce with the following test page:

```
<!DOCTYPE html>
<html>
<body>

<button onclick="sendRequest()">Send Request</button>

<script>
function sendRequest() {
  fetch('https://api.pushbullet.com/v3/set-app-state', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: '',
  })
  .then(response => response.json())
  .then(data => console.log(data))
  .catch((error) => console.error('Error:', error));
}
</script>

</body>
</html>
```

Looks like the block rule is coming from the community lists:
```
||pushbullet.com^$third-party
```

I disabled the rule now: https://github.com/ghostery/broken-page-reports/commit/dc3b7aa72a5e82323635012ed093d4c6e4a284a1

@rnatella It may take a bit, but the change to the adblocker list should be ready to test relatively soon. If you can still reproduce problem tomorrow, we have to take a closer look.

**Comment by philipp-classen** [comment]
@rnatella Just realized that on Edge (being Manifest V3) it will take an extension release to have an effect. But on Firefox, it should be possible to test it before if you want.

But I will leave a note here once the next extension release for Edge is out.

**Comment by philipp-classen** [comment]
Edge has been updated (Ghostery 10.3.5).

**Comment by rnatella** [comment]
It works! Thanks again.

**Comment by philipp-classen** [comment]
@rnatella Thanks for checking!
