### ISSUE TITLE
How to report a false block?

### ISSUE THREAD

**Issue by Mishasama** [ghostery/trackerdb#407]
The Microsoft Rewards on Bing do not work after Ghostery is turned on.

![image](https://github.com/user-attachments/assets/e9ebce5d-45b4-40cf-9a4c-25b1a9ffd435)

**Comment by philipp-classen** [comment]
For site breakage in Ghostery, you can report it here: https://github.com/ghostery/broken-page-reports/

It helps to include the steps on how to reproduce it. Also, please explain what functionality is broken with Ghostery enabled, and how the site is intended to work (if it was not broken).

**Comment by Mishasama** [comment]
Thanks!
