### ISSUE TITLE
The #teconsent (Cookie Preferences link) from TrustArc is being blocked by a filter added recently

### ISSUE THREAD

**Issue by hyebahi** [ghostery/trackerdb#412]
### Request

N/A

### Location

https://oracle.com

### Tracker Company

TrustArc

### Category

Consent Management

### Request Type

None

### Additional Information

A change from 3 months for OneTrust: added a rule to block the div with id#teconsent. This div is responsible for loading the "cookie preferences" from TrustArc.
Is it possible to remove this rule to allow users to change their preferences?
Here is the commit with the filter added
https://github.com/ghostery/trackerdb/commit/2556ac7430ec8cc634788422622a080c27c2fdeb

Thank you

### Filters

```shell
###teconsent
```

**Comment by philipp-classen** [comment]
Thank you for reporting. But I think it is not a problem in TrackerDB. Perhaps a community list filter hides it.

I can reproduce on oracle.com, so I opened a ticket here: https://github.com/ghostery/broken-page-reports/issues/806

**Comment by philipp-classen** [comment]
`###teconsent` comes from EasyList - Cookie Notices. Adding the following custom filter fixes it:

```
#@##teconsent
```

I'll close this one. Please follow the fix on https://github.com/ghostery/broken-page-reports/issues/806

**Comment by hyebahi-trustarc** [comment]
Thank you for getting back to me so quickly! I appreciate it.
