### ISSUE TITLE
[Unidentified Tracker]: plausible.io

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/trackerdb#49]
### Request

plausible.io

### Location

(needs investigation)

### Tracker Company/Organization

Plausible

### Company/Organization Website

https://plausible.io/

### Company/Organization Privacy Policy

https://plausible.io/privacy

### Describe the company/organization

Plausible is intuitive, lightweight and open source web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. Made and hosted in the EU, powered by European-owned cloud infrastructure

**Comment by philipp-classen** [comment]
Example page: https://www.stacks.co/
