### ISSUE TITLE
Documentation: README const trackerDB = await loadTrackerDB();  does not match function signature

### ISSUE THREAD

**Issue by stewartschillingsdi** [ghostery/trackerdb#56]
README docs show usage as: 
 const trackerDB = await loadTrackerDB();

TypeScript complains.
index.d.ts(5, 45): An argument for 'engineBytes' was not provided.
(alias) loadTrackerDB(engineBytes: Uint8Array): Promise<{
    ENGINE_VERSION: number;
    engine: FilterEngine;
    matchUrl(requestArgs: Partial<RequestInitialization>, getPatternMetadataParams?: {
        ...;
    } | undefined): IPatternLookupResult[];
    matchDomain(domain: string): IPatternLookupResult[];
}>

Please update the example with a param value for 'engineBytes'. 

Thanks!

**Comment by philipp-classen** [comment]
Thanks for spotting that! We fix that.

I do not know if it is the proper way to do it, but this here should execute:
```
import { readFileSync } from 'node:fs';
import path from 'node:path';
import * as url from 'url';
import loadTrackerDB from '@ghostery/trackerdb';
import { FiltersEngine } from '@cliqz/adblocker';

const __dirname = url.fileURLToPath(new URL('.', import.meta.url));
const enginePath = path.join(__dirname, './node_modules/@ghostery/trackerdb/dist/trackerdb.engine');

const engine = readFileSync(enginePath);
const trackerDB = await loadTrackerDB(engine);

const domainMatches = await trackerDB.matchDomain('google.com');

const urlMatches = await trackerDB.matchUrl({
    url: 'https://google.com/gen_204',
    type: 'xhr',
    sourceUrl: 'https://google.com/'
}, {
    getDomainMetadata: true,
});
```

**Comment by philipp-classen** [comment]
Simplified example: https://github.com/ghostery/trackerdb/pull/57
